language: cpp
os: 
  -linux
compiler:
  - gcc
  
install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:robotology/ppa; sudo apt-get update; sudo apt-get install cmake; fi
  - cmake --version


before_script:
- git clone https://github.com/robotology/ycm.git
- cd ycm
- mkdir build
- cd build
- cmake ../
- make
- sudo make install
- cd ../../

- git clone https://github.com/tacman-fp7/template-pkg.git
- cd template-pkg
- mkdir build
- cd build
- cmake ../
- make
- set Template-Pkg_DIR=${PWD}
- cd ../../
- mkdir build

# Change this to your needs
script: 
- echo ${Template-Pkg_DIR}
- cd build
- cmake ../
- make

