language: cpp
os: 
  -linux
compiler:
  - gcc
  
install:

  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:robotology/ppa; sudo apt-get update; sudo apt-get install cmake; fi
  - cmake --version


before_script:
- cmake --version
- git clone https://github.com/robotology/ycm.git
- cd ycm
- mkdir -p build
- cd build
- cmake ../
- make
- sudo make install

- git clone https://github.com/tacman-fp7/template-pkg.git
- cd template-pkg
- mkdir build -p
- cd build
- cmake ../
- make
- set template-pkg_DIR=${PWD}
- cd ../../
- mkdir -p build

# Change this to your needs
script: 
- cd build
- cmake ../
- make

